### ISSUE TITLE
Mismatch in decrypt output and original file

### ISSUE THREAD

**Issue by svelucse** [BroadcomMFD/broadcom-product-scripts#12]
Hi,
We are trying this code.

Below are the issue.

1) We are getting some  differences in AZUCFG,AZUGEN and AZURES PDS datasets. A last bytes is getting messed up during encryption and decryption process.

2) Last 4 -5 bytes are getting messed up AZUSCH and AZUTDT these two files have multi line data and length of the record is 16379. During encryption it looks like it is increasing this to 16380 then adding four bytes which cannot fit in the output compress file whose length is 16387.

Is there a solution for these two.

**Comment by waljo11** [comment]
Looking into it.......

**Comment by waljo11** [comment]
Testing a fix for this.

**Comment by waljo11** [comment]
Working a Pull Request.
